# Generated by Django 5.1.2 on 2024-10-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Иконка категории')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='loft.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('color_name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('color_code', models.CharField(default='#ffffff', max_length=10, verbose_name='Код цвета')),
                ('width', models.CharField(max_length=10, verbose_name='Ширина')),
                ('depth', models.CharField(max_length=10, verbose_name='Глубина')),
                ('height', models.CharField(max_length=10, verbose_name='Высота')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loft.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loft.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
