# Generated by Django 5.1.2 on 2024-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес доставки (улица, дом, кв)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Регион'),
        ),
    ]
